import {
    faHatWizard,
    faTrashCan,
    faPencil,
    faCloudUpload,
    faFileExport,
    faArrowLeft,
    faArrowRight,
    faSignOut,
    faSignOutAlt,
    faList,
    faCartShopping,
    faEdit,
    faUserEdit,
    faUser,
    faFileEdit,
    faHome,
    faArrowUp,
    faArrowDown,

    faPeopleGroup,
    faFileLines,
    faArrowTrendUp,
    faChevronRight,
    faImage,
    faImages,
    faChevronDown,
    faChevronUp,
    faSearch,
    faCartArrowDown,
    faFire,
    faBars,
    faXmark,
    faStar,
    faFaceFrown,
    faCoins, faTicket, faCheckCircle, faArrowUpWideShort, faArrowDownShortWide, faBorderAll,
} from "@fortawesome/free-solid-svg-icons";

import { library } from "@fortawesome/fontawesome-svg-core";
// 加入所需ICON
library.add(
    faHatWizard,
    faTrashCan,
    faPencil,
    faEdit,
    faUserEdit,
    faCloudUpload,
    faFileExport,
    faArrowLeft,
    faArrowRight,
    faSignOut,
    faSignOutAlt,
    faList,
    faCartShopping,
    faFileEdit,
    faSearch,
    faHome,
    faArrowUp,
    faArrowDown,
    faCoins,
    faPeopleGroup,
    faFileLines,
    faArrowTrendUp,
    faChevronRight,
    faImage,
    faImages,
    faChevronDown,
    faUser,
    faCartArrowDown,
    faFire,
    faBars,
    faXmark, faStar, faFaceFrown, faTicket, faCheckCircle, faArrowUpWideShort, faArrowDownShortWide, faChevronUp, faBorderAll
); 
